"""empty message

Revision ID: 9988840acb76
Revises: 30e8f0a1b030
Create Date: 2022-01-29 08:39:03.002042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9988840acb76'
down_revision = '30e8f0a1b030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE xp_user SET public_id = 'ed80b7f7a0dbfbd8ec0f'")
    op.alter_column('xp_user', 'public_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'xp_user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xp_user', type_='unique')
    op.alter_column('xp_user', 'public_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
